version: "3.8"
services:

  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:80
    volumes:
      - ./:/var/www/html
      - finki-forum-images:/var/www/html/resources/uploads/images
      - finki-forum-user-avatars:/var/www/html/resources/uploads/user_avatars
      - finki-forum-videos:/var/www/html/resources/uploads/videos
      - finki-forum-videos-thumbnails:/var/www/html/resources/uploads/videos_thumbnails
    depends_on:
      - mongo
    environment:
      - BASE_URL=${BASE_URL}
      - MONGO_SERVER=finki-forum-mongo-db
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - finki-forum-network
  
  mongo:
    image: mongo:3.6
    container_name: finki-forum-mongo-db
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      # init finki_forum db data - create admin user and a forum with subforums
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - finki-forum-mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - finki-forum-network

networks:
  finki-forum-network:

volumes:
  finki-forum-mongo-data:
  finki-forum-images:
  finki-forum-user-avatars:
  finki-forum-videos:
  finki-forum-videos-thumbnails: