# This is a basic workflow to help you get started with Actions

name: DIGITALOCEAN_DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Create .env
        run: |
          echo 'BASE_URL=${{ secrets.BASE_URL }}' >> .env
          echo 'PORT=${{ secrets.PORT }}' >> .env
          echo 'MONGO_DBNAME=${{ secrets.MONGO_DBNAME }}' >> .env
          echo 'MONGO_PORT=${{ secrets.MONGO_PORT }}' >> .env
          echo 'MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}' >> .env
          echo 'MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}' >> .env
          echo 'MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}' >> .env
          echo 'MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}' >> .env

      # Runs a set of commands using the runners shell
      - name: Change permissions for uploads folders
        run: chmod -R 777 resources

      # Runs a set of commands using the runners shell
      - name: Run build
        run: docker-compose up --scale webapp=3 -d
